<?php get_header(); ?>
<div class="main_content author_profile pure-g-r">
<?php
	/////////////////////////////
	// CUSTOM POST TYPE METADATA
	/////////////////////////////
	
		$curauth = (isset($_GET['author_name'])) ? get_user_by('slug', $author_name) : get_userdata(intval($author)); // get the current author profile information, per http://codex.wordpress.org/Author_Templates
	
		$authorID = $curauth->ID;
		$authorName = $curauth->display_name;
		$authorWebsite = $curauth->user_url; // get custom field for compsny/artist website -- OPTIONAL
		$authorBio = $curauth->description; // get the author's bio from their user account
		$twitterHandle = types_render_usermeta_field( "twitter-handle", array("raw"=>"true", "user_id" => $authorID)); // get custom field for company/artist twitter handle -- OPTIONAL
		$authorPhoto = types_render_usermeta_field( "author-photo", array("raw"=>"true", "user_id" => $authorID)); // get URL for author image
		$commissionWords = types_render_usermeta_field("commission-random-words", array("raw"=>"true", "user_id" => $authorID)); // get the random words they used as a starting point for their commission
		$authorLongitude = types_render_usermeta_field("author-longitude", array("raw"=>"true", "user_id" => $authorID)); // get author longitude
		$authorLatitude = types_render_usermeta_field("author-latitude", array("raw"=>"true", "user_id" => $authorID)); // get author latitude
		$authorTimezone = types_render_usermeta_field("author-timezone", array("raw"=>"true", "user_id" => $authorID)); // get author timezone as entered in their profile
		
		if($authorPhoto){
			// Function to replace the upload-sized author photo with the 300px-square one
			$findImgExt = "/(\.jpg|\.jpeg|\.png)$/";
			$addThumbDimension = "-300x300$1";
			$authorPhoto = preg_replace($findImgExt, $addThumbDimension, $authorPhoto);
		}		
	?>
	
	<header class="pure-u-1">
		<h1 id="<?php echo($authorID); ?>"><?php echo $authorName; ?></h1>
	</header>
	
	<div class="pure-u-1-2">
		<?php if($authorPhoto) : ?>
		<figure>
			<img src="<?php echo $authorPhoto; ?>" alt="<?php echo $authorName; ?>" />
		</figure>
		<?php endif; ?>
		<?php if($authorBio){ echo '<p>'.$authorBio.'</p>'; } ?>
		<?php if($authorWebsite){ echo '<p><a href="'.$authorWebsite.'" class="author-website" title="Visit '.$authorName.'&rsquo;s website" target="_blank">Website <i class="icon-external-link"></i></a></p>'; } ?>
		<?php if($twitterHandle) : ?><a class="twitter-timeline" href="https://twitter.com/<?php echo $twitterHandle; ?>" data-screen-name="<?php echo $twitterHandle; ?>" data-related="spiderwebshow" data-widget-id="365853013174276096">Tweets by <?php echo $twitterHandle; ?></a><?php endif; ?>
		<?php if($authorLongitude && $authorLatitude) : ?>
			<h2><?php echo $authorName; ?>&rsquo;s location</h2>
			<p class="author-time"></p>
			<div id="author-map"></div>
		<?php endif; ?>
	</div>	
	
	<div class="pure-u-1-2">
	
	<?php // Loop for the Commission videos, if there is one
		if($commissionWords){		
			$args = array (
				'post_type'              => 'commission', // get Commission post-types only
				'posts_per_page'         => '1', // get only one of them
				'author'								 => strval($authorID) // get only the one by the author whose page we're on
			);
			
			// The Query
			$query = new WP_Query( $args );
			
			// The Loop
			if ( $query->have_posts() ) {
				while ( $query->have_posts() ) {
					$query->the_post();
					
					$youtubeUrl = types_render_field("youtube-url", array("raw"=>"true")); // get custom field for the youtube video -- REQUIRED
					if($youtubeUrl){ // Isolate just the video ID from the Youtube URL
						$idPattern = "/\?v=([\w-]{11})/"; // Regex for the 11-character video id
						preg_match($idPattern, $youtubeUrl, $temp_vID);
						$vID = ($temp_vID[1]);
					} ?>
					
			<div style="background:#444;color:#fff;padding:1em;">
				<h2>The Commission</h2>
				<p><?php echo $authorName; ?> was commissioned by SpiderWebShow to produce a piece of one-minute smartphone theatre based on the following five words (as randomly generated by <a href="http://passphra.se" title="Visit Passphra.se" style="color:#fff;">passphra.se</a>):</p>
				<p style="padding:1em;background:#fff;color:#444;font-family:monospace;font-size:1.6666em;text-align:center;"><?php echo $commissionWords; ?></p>
				<p>...and here is the result:</p>
				<figure class="youtube embed" data-youtube-id="<?php echo $vID; ?>"></figure>
			</div>		
					
			<?php	}
			} else {
				// no posts found
			}
			
			// Restore original Post Data
			wp_reset_postdata();
		// end if $commissionwords
		}
		?>
		
		<?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
		<h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
		<p><time datetime="<?php the_time('c'); ?>"><?php the_time('F j, Y') ?></time></p>
		<?php the_excerpt(); ?>
				
		<?php endwhile; else: ?>
		<p><?php _e(''); ?></p>
		<?php endif; ?>
		
	</div>
	
	
	<script>
		head.ready(function(){
			
			var target, vid, insert;
			target = $('figure.youtube.embed');
			vid = target.data('youtube-id');
			insert = $('<iframe/>');
			insert.attr('src', '//www.youtube-nocookie.com/embed/'+vid+'?rel=0')
						.attr('frameborder', '0')
						.prop('allowfullscreen');
			target.append(insert).fitVids();
			
			
	<?php if($authorLongitude && $authorLatitude) : // Send this script only if the Author LongLat has been provided ?>
	
			// Function to display a map with the author's location on it.
			
			var authorMap = L.mapbox.map('author-map', 'spiderwebshow.gghgd327') // we have a blank mapbox map
	    .setView([<?php echo $authorLatitude; ?>, <?php echo $authorLongitude; ?>], 12); // set the view and zoom with the author's information
	
			L.mapbox.markerLayer({ // new markerLayer instance, using geoJSON
			    type: 'Feature',
			    geometry: {
			        type: 'Point',
			        // coordinates here are in longitude, latitude order because
			        // x, y is the standard for GeoJSON and many formats
			        coordinates: [<?php echo $authorLongitude; ?>, <?php echo $authorLatitude; ?>] // coords are the same, only backward because MapBox sets view and coordinates in opposite order. Lost a few hours to that today.
			    },
			    properties: {
			        title: '<?php echo $authorName; ?>', // display the author's name in the popup
			        'marker-size': 'large',
			        'marker-color': '#b00'
			    }
			}).addTo(authorMap);
			
			// Daylight Savings Time Fixes
			// http://javascript.about.com/library/bldst.htm
			// http://stackoverflow.com/questions/11887934/check-if-daylight-saving-time-is-in-effect-and-if-it-is-for-how-many-hours
			Date.prototype.stdTimezoneOffset = function() {
        var jan = new Date(this.getFullYear(), 0, 1);
        var jul = new Date(this.getFullYear(), 6, 1);
        return Math.max(jan.getTimezoneOffset(), jul.getTimezoneOffset());
        }
			Date.prototype.dst = function() {
        return this.getTimezoneOffset() < this.stdTimezoneOffset();
        }
			
			// Function to grab the current time where the author is, given the time where the visitor is
			function authorTime(offset) {
        
		    // get the client's current time
		    var clientTime = new Date();
		    if (clientTime.dst()){
  		    offset = offset + 1;
		    }
		    
		    // get UTC time compared to the client in milliseconds
		    var utc = clientTime.getTime() + (clientTime.getTimezoneOffset() * 60000);
		    
		    var authorTime = new Date(utc + (3600000 * offset)); // get the author's local time, since we have their hour differential from the timezone setting
		    
		    var authorHour = authorTime.getHours(); // what's the hour there?
		      // if it's PM, subtract 12 to get the 12-hour clock version of the hour.
		      if(authorHour >= 12) {
  		      authorHour = authorHour - 12;
		      }
		      
		      if(authorHour === 0) {
  		      authorHour = "00";
		      }		      	    
		    		    
        var authorMinute = authorTime.getMinutes(); // what's the minute there?
  	      // If there's only one digit returned add a preceding zero
		      authorMinute.toString();
		      if(authorMinute.length == 1) {
  		      authorMinute = "0" + authorMinute;
		      }
		    	    
		    var output = authorHour + ":" + authorMinute; // combine it into one string
		    
		    return output; // output the result
		    
		}
		
		var thisAuthorTime = authorTime(<?php echo $authorTimezone; ?>);
		var authorTimeMessage = "It's now " + thisAuthorTime + " there.";
		$('.author-time').append(authorTimeMessage);
		
					
	<?php endif; // End of $authorLongLat script snippet ?>	
			
		});
		
	</script>
	
	
	
</div>
<?php get_footer(); ?>